//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassesTrans
    {
        public int ID { get; set; }
        public string StudentID { get; set; }
        public string ClassFrom { get; set; }
        public string ClassTo { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string CreatorId { get; set; }
        public string Remark { get; set; }
    }
}
