//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProvider
{
    using DapperExtensions.Mapper;
    using System;
    using System.Collections.Generic;
    
    public partial class Discount
    {
        /// <summary>
        /// 优惠表主键
        /// </summary>
        public int ID { get; set; }
        /// <summary>
        /// 优惠名称
        /// </summary>
        public string DiscountName { get; set; }
        /// <summary>
        /// 优惠条件
        /// </summary>
        public string Condition { get; set; }
        /// <summary>
        /// 优惠类型，字典表，打折或者减免
        /// </summary>
        public Nullable<int> DiscountTypeID { get; set; } 
        /// <summary>
        /// 折扣率，比如9.0 就是9折
        /// </summary>
        public Nullable<decimal> DiscountRate { get; set; }
        /// <summary>
        /// 减免金额
        /// </summary>
        public Nullable<decimal> ReduceAmount { get; set; }
        /// <summary>
        /// 优惠的开始时间
        /// </summary>
        public Nullable<System.DateTime> BeginTime { get; set; }
        /// <summary>
        /// 优惠的结束时间
        /// </summary>
        public Nullable<System.DateTime> EndTime { get; set; }
        /// <summary>
        /// 状态ID，优惠状态，字典表
        /// </summary>
        public Nullable<int> StateID { get; set; }
        /// <summary>
        /// 备注
        /// </summary>
        public string Remarks { get; set; }
        public string CreatorId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string UpdatorId { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string DeletorId { get; set; }
        public Nullable<System.DateTime> DeleteTime { get; set; }
    }

    /// <summary>
    /// Deploy：实体对象映射关系
    /// </summary>
    [Serializable]
    public sealed class DiscountORMMapper : ClassMapper<Discount>
    {
        public DiscountORMMapper()
        {
            base.Table("Discount");

            //Map(f => f.socketouts).Ignore();//设置忽略
            Map(f => f.ID).Key(KeyType.Identity);//设置主键  (如果主键名称不包含字母“ID”，请设置)      
            AutoMap();
        }
    }

}
