//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Enroll
    {
        public string ID { get; set; }
        public string APID { get; set; }
        public string StudentID { get; set; }
        public string ClassID { get; set; }
        public decimal ClassHour { get; set; }
        public decimal UsedHour { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Paid { get; set; }
        public string DiscountID { get; set; }
        public Nullable<decimal> DiscountPrice { get; set; }
        public string CreatorId { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string UpdatorId { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string DeletorId { get; set; }
        public Nullable<System.DateTime> DeleteTime { get; set; }
        public string Remark { get; set; }
        public int StateID { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedTime { get; set; }
        public string ApprovedRemark { get; set; }
        public string Name { get; set; }
        public string BindPhone { get; set; }
    }
}
