//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_FollowList
    {
        public int ID { get; set; }
        public string APID { get; set; }
        public int FollowTypeID { get; set; }
        public int IntenID { get; set; }
        public string Remark { get; set; }
        public System.DateTime FollowTime { get; set; }
        public string FollowPersonID { get; set; }
        public string ApName { get; set; }
        public string ApTel { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string DicItemName { get; set; }
        public string DicItemName1 { get; set; }
    }
}
